import React,{useState} from 'react';
import {createRoot} from 'react-dom/client';
import {ArrowRight, Menu, X, Check, MapPin, Mail, Phone, ChevronDown, Sparkles} from 'lucide-react';
import './styles.css';

const focus=[
 ['Anxiety & Panic','Build steadier ways to respond to worry, tension, overthinking, and the feeling that something might go wrong.'],
 ['Trauma & Past Experiences','Carefully paced support for single-incident trauma and longer-standing patterns shaped by childhood, relationships, or chronic stress.'],
 ['Burnout & Perfectionism','A space to step out of constant pressure, reconnect with yourself, and develop more sustainable ways of living and working.']
];
const faqs=[
 ['Do you offer in-person therapy?','Yes. Dr. Maya Reynolds offers in-person therapy from her quiet, private Santa Monica office.'],
 ['Do you offer telehealth?','Yes. Secure telehealth sessions are available for clients located in California.'],
 ['Who do you work with?','Dr. Reynolds works with adults, including high-achieving professionals, entrepreneurs, and creatives experiencing anxiety, trauma, burnout, perfectionism, or high internal pressure.'],
 ['What approaches do you use?','Her work integrates evidence-based methods including CBT, EMDR, mindfulness-based practices, and body-oriented techniques.']
];
function App(){const [open,setOpen]=useState(null);const [menu,setMenu]=useState(false); return <div>
<header className="nav"><div className="wrap navin"><a className="brand" href="#top"><span className="brandmark">MR</span><span><b>Dr. Maya Reynolds</b><small>PsyD · Clinical Psychologist</small></span></a><button className="menubtn" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button><nav className={menu?'open':''}>{[['About','#about'],['Focus','#focus'],['Approach','#approach'],['Our Office','#office'],['FAQs','#faqs']].map(([x,y])=><a key={x} href={y} onClick={()=>setMenu(false)}>{x}</a>)}<a className="navcta" href="#contact" onClick={()=>setMenu(false)}>Schedule a Consultation <ArrowRight size={16}/></a></nav></div></header>
<main id="top">
<section className="hero"><div className="hero-shape"></div><div className="wrap hero-grid"><div className="hero-copy"><p className="eyebrow">THERAPY IN SANTA MONICA · CALIFORNIA TELEHEALTH</p><h1>A steadier way forward starts with feeling understood.</h1><p className="lead">Warm, grounded therapy for adults navigating anxiety, panic, trauma, burnout, and the pressure to keep everything together.</p><div className="actions"><a className="btn primary" href="#contact">Schedule a consultation <ArrowRight size={18}/></a><a className="textlink" href="#about">Meet Dr. Reynolds <ArrowRight size={16}/></a></div><div className="trust"><span><Check size={15}/>In-person in Santa Monica</span><span><Check size={15}/>Secure California telehealth</span></div></div><div className="hero-photo"><div className="photo-frame"><img src="/images/maya.jpg" alt="Dr. Maya Reynolds"/></div><div className="photo-note"><Sparkles size={17}/><span><b>Warm. Collaborative. Grounded.</b><small>Practical tools with room for depth.</small></span></div></div></div></section>
<section className="intro" id="about"><div className="wrap narrow"><p className="eyebrow">A SPACE TO SLOW DOWN</p><h2>You can look functional on the outside and still feel exhausted inside.</h2><p>Many of the people Dr. Reynolds works with are thoughtful, self-aware, and high-achieving—but privately feel stuck in overthinking, emotionally on edge, or disconnected from themselves. Therapy can offer a place to understand what is happening, feel more regulated, and move toward a life that feels more sustainable.</p></div></section>
<section className="focus section" id="focus"><div className="wrap"><div className="sectionhead"><div><p className="eyebrow">AREAS OF FOCUS</p><h2>Support for what you're carrying.</h2></div><p>Therapy is tailored to your experience, with attention to both the emotional and physiological sides of what you're experiencing.</p></div><div className="cards">{focus.map(([t,d],i)=><article className="card" key={t}><span className="num">0{i+1}</span><h3>{t}</h3><p>{d}</p><a href="#contact">Explore therapy <ArrowRight size={16}/></a></article>)}</div></div></section>
<section className="statement"><div className="wrap statementin"><div className="quote">“</div><h2>Therapy can be a place to slow down, reconnect, and develop more sustainable ways of living and working.</h2><p>Especially when you've spent years pushing through.</p></div></section>
<section className="approach section" id="approach"><div className="wrap approachgrid"><div className="approachcopy"><p className="eyebrow">HOW I WORK</p><h2>Practical tools, with room for depth.</h2><p>I take a warm, collaborative, and grounded approach. Sessions are structured enough to feel supportive while leaving space for reflection and depth.</p><p>I integrate <b>CBT, EMDR, mindfulness-based practices,</b> and <b>body-oriented techniques</b> to help you understand patterns and build greater regulation in daily life.</p><a className="btn outline" href="#contact">Let's connect <ArrowRight size={18}/></a></div><div className="approachlist"><div><span>01</span><b>Safety & stabilization</b><p>Trauma work is paced carefully, with an emphasis on safety and feeling more regulated—not just during sessions.</p></div><div><span>02</span><b>Insight & resilience</b><p>The goal goes beyond symptom relief toward insight, resilience, and a stronger relationship with yourself.</p></div><div><span>03</span><b>Active collaboration</b><p>You remain actively involved in the process, with care that respects your experience and goals.</p></div></div></div></section>
<section className="aboutband"><div className="wrap aboutgrid"><div className="portrait"><img src="/images/maya.jpg" alt="Dr. Maya Reynolds, PsyD"/></div><div><p className="eyebrow">ABOUT DR. MAYA REYNOLDS, PSYD</p><h2>A therapist who understands the realities of a fast-paced life.</h2><p>Dr. Maya Reynolds is a licensed clinical psychologist based in Santa Monica, California. She works with adults who feel overwhelmed by anxiety, stress, or the lingering effects of past experiences.</p><p>Her practice often supports professionals, entrepreneurs, and creatives navigating burnout, perfectionism, high internal pressure, trauma, and anxiety.</p><p>Her goal is to create a therapy relationship where clients feel respected, understood, and actively involved in the work.</p></div></div></section>
<section className="office section" id="office"><div className="wrap"><div className="sectionhead officehead"><div><p className="eyebrow">OUR OFFICE</p><h2>A quiet place to feel more at ease.</h2></div><p>Dr. Reynolds' Santa Monica office is designed to feel calm and grounding, with natural light and a comfortable, uncluttered environment.</p></div><div className="officegrid"><img src="/images/office-1.jpg" alt="Comfortable therapy office with natural light"/><img src="/images/office-2.jpg" alt="Private therapy room"/><div className="officecard"><MapPin size={20}/><h3>Santa Monica, California</h3><p>123th Street 45 W<br/>Santa Monica, CA 90401</p><span>In-person therapy · Secure telehealth across California</span></div></div></div></section>
<section className="faqs section" id="faqs"><div className="wrap faqgrid"><div><p className="eyebrow">QUESTIONS</p><h2>Frequently asked questions.</h2><p className="muted">A few helpful details before you reach out.</p></div><div>{faqs.map(([q,a],i)=><div className="faq" key={q}><button onClick={()=>setOpen(open===i?null:i)}><span>{q}</span><ChevronDown className={open===i?'rot':''}/></button>{open===i&&<p>{a}</p>}</div>)}</div></div></section>
<section className="contact" id="contact"><div className="wrap contactin"><div><p className="eyebrow light">TAKE THE NEXT STEP</p><h2>You don't have to keep pushing through alone.</h2><p>If you're looking for a therapist who combines practical tools with depth-oriented work, reach out to begin a conversation.</p></div><div className="contactbox"><a href="mailto:hello@mayareynoldspsyd.com"><Mail size={18}/>Email Dr. Reynolds</a><a href="tel:+13105550145"><Phone size={18}/>Schedule by phone</a><span><MapPin size={18}/>Santa Monica, CA</span></div></div></section>
</main><footer><div className="wrap footerin"><div><a className="brand footbrand" href="#top"><span className="brandmark">MR</span><span><b>Dr. Maya Reynolds</b><small>PsyD · Clinical Psychologist</small></span></a><p>Warm, grounded therapy for adults in Santa Monica and across California via secure telehealth.</p></div><div className="footlinks"><a href="#about">About</a><a href="#focus">Focus</a><a href="#office">Our Office</a><a href="#contact">Contact</a></div></div><div className="wrap copyright">© 2026 Dr. Maya Reynolds, PsyD · Fictional therapist profile · Santa Monica, California</div></footer>
</div>}
createRoot(document.getElementById('root')).render(<App/>);
